### ISSUE TITLE
Remove excess styles

### ISSUE THREAD

**Issue by abinxzh** [zachacole/Simple-Grid#2]
There's a lot of code at the start of this that gives styles for fonts and typography. This is not what i expect out of a simple grid – which should be simply a grid. I recommend removing this and implementing them as another repo (so as to not make this into yet another framework).
- Jeff

**Comment by zachacole** [comment]
Hey Jeff - thanks for the feedback! The issue of included type styles has been brought up by a few others as well. I included them initially because I believe that strong web design is largely based around working within a grid, and strong type setting. I understand that people may choose to overwrite the type styles, but I felt strongly about included a baseline suggestion that provides clear vertical rhythm.
